### ISSUE TITLE
while parsing a quoted scalar, found unknown escape character

### ISSUE THREAD

**Issue by mrowcp** [PoC-Consortium/scavenger#6]
Windows 10 error:

> thread 'main' panicked at 'failed to parse config yaml: Scan(ScanError { mark: Marker { index: 66, line: 4, col: 2 }, info: "while parsing a quoted scalar, found unknown escape character" })', libcore\result.rs:945:5
> 
> note: Run with `RUST_BACKTRACE=1` for a backtrace.

Here is the config:

```
secret_phrase: ""
account_id: 8961560224519517741
plot_dirs:
"T:\plots"
"J:\plots"
"R:\plots"
"G:\plots"
"I:\plots"
"K:\plots"
"E:\plots"
"S:\plots"
"Y:\plots"
"V:\plots"
"W\\plots"
"N:\plots"
"Q:\plots"
"H:\plots"
"U:\plots"
"L:\plots"
"P:\plots"
"O:\plots"
"M:\plots"
"X:\plots"
url: "http://pool.changed.website:8124"
# url: "http://pool.dev.burst-test.net:8124"
worker_thread_count: 1
reader_thread_count: 1
nonces_per_cache: 65536 # default 65536
target_deadline: 10885484741537822773 # default u64::MAX
use_direct_io: true # default true
get_mining_info_interval: 3000 # default 3000ms
```

target_deadline was reduced to 1299774 (I'm using 0-100 calculator), but same error appear.

**Comment by spebern** [comment]
the format of your plot_dirs is wrong:

```yaml 
secret_phrase: ""
account_id: 8961560224519517741
plot_dirs:
  - "T:\plots"
  - "J:\plots"
  - "R:\plots"
  - "G:\plots"
  - "I:\plots"
  - "K:\plots"
  - "E:\plots"
  - "S:\plots"
  - "Y:\plots"
  - "V:\plots"
  - "W\\plots"
  - "N:\plots"
  - "Q:\plots"
  - "H:\plots"
  - "U:\plots"
  - "L:\plots"
  - "P:\plots"
  - "O:\plots"
  - "M:\plots"
  - "X:\plots"
url: "http://pool.changed.website:8124"
# url: "http://pool.dev.burst-test.net:8124"
worker_thread_count: 1
reader_thread_count: 1
nonces_per_cache: 65536 # default 65536
target_deadline: 10885484741537822773 # default u64::MAX
use_direct_io: true # default true
get_mining_info_interval: 3000 # default 3000ms
```
